# Generated by Django 6.0.5 on 2026-06-08 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        help_text="e.g. 2021-1-60-001", max_length=20, unique=True
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        choices=[
                            ("BSc_CSE", "BSc in Computer Science & Engineering"),
                            ("BSc_EEE", "BSc in Electrical & Electronic Engineering"),
                            ("BSc_CE", "BSc in Civil Engineering"),
                            ("BSc_GEB", "BSc in Genetic Engineering & Biotechnology"),
                            ("BSc_Pharmacy", "BSc in Pharmacy"),
                            ("BBA", "Bachelor of Business Administration"),
                            ("LLB", "Bachelor of Laws (LLB)"),
                            ("BA_English", "BA in English"),
                            ("BA_SocialRel", "BA in Social Relations"),
                            ("BSc_InfoStudy", "BSc in Information Studies"),
                            ("BSc_Sociology", "BSc in Sociology"),
                            ("BSc_Economics", "BSc in Economics"),
                            ("MBA", "Master of Business Administration"),
                            ("EMBA", "Executive MBA"),
                            ("MSc_CSE", "MSc in Computer Science & Engineering"),
                            ("LLM", "Master of Laws (LLM)"),
                            ("MA_English", "MA in English"),
                        ],
                        default="BSc_CSE",
                        max_length=30,
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("Spring", "Spring"),
                            ("Summer", "Summer"),
                            ("Fall", "Fall"),
                        ],
                        default="Spring",
                        max_length=10,
                    ),
                ),
                ("year", models.IntegerField(default=2024)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="students/pics/"
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True)),
                (
                    "is_verified",
                    models.BooleanField(default=False, help_text="Email verified"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Profile",
                "verbose_name_plural": "Student Profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
