# Generated by Django 6.0.5 on 2026-06-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "badge_color",
                    models.CharField(
                        choices=[
                            ("green", "Green"),
                            ("red", "Red"),
                            ("blue", "Blue"),
                            ("orange", "Orange"),
                        ],
                        default="green",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="ImportantDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Calendar"),
                            ("exam", "Examination"),
                            ("holiday", "Holiday"),
                            ("admission", "Admission"),
                            ("result", "Result"),
                            ("other", "Other"),
                        ],
                        default="academic",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Important Date",
                "ordering": ["date"],
            },
        ),
    ]
