# Generated by Django 6.0.5 on 2026-06-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_chatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="sender",
            field=models.CharField(
                choices=[("user", "User"), ("bot", "Bot")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="session_key",
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
