# Generated by Django 6.0.5 on 2026-06-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_chatmessage_sender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="news/"),
        ),
    ]
