# Generated by Django 6.0.5 on 2026-06-04 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_achievement"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Gallery Category",
                "verbose_name_plural": "Gallery Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("cse", "CSE"),
                            ("eee", "EEE"),
                            ("bba", "BBA"),
                            ("pharmacy", "Pharmacy"),
                            ("economics", "Economics"),
                            ("english", "English"),
                            ("law", "Law"),
                            ("admin", "Administration"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contractual", "Contractual"),
                            ("adjunct", "Adjunct"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Full job description. Supports plain text."
                    ),
                ),
                (
                    "requirements",
                    models.TextField(blank=True, help_text="One requirement per line."),
                ),
                (
                    "how_to_apply",
                    models.TextField(blank=True, help_text="Application instructions."),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Job Opening",
                "ordering": ["-posted_at"],
            },
        ),
        migrations.CreateModel(
            name="GalleryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="gallery/")),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="main.gallerycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Photo",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
