# Generated by Django 6.0.5 on 2026-06-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_gallerycategory_job_galleryphoto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slider",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="slider",
            name="badge",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="slider",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
